"""make kozu_project_datas table

Revision ID: 0088aec53b0e
Revises: af2a6abc9162
Create Date: 2024-10-26 19:50:29.136815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0088aec53b0e'
down_revision: Union[str, None] = 'af2a6abc9162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kozu_project_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_data_id', sa.Integer(), nullable=False),
    sa.Column('is_gabion', sa.Boolean(), nullable=False),
    sa.Column('sp_wind_reg', sa.String(length=5), nullable=False),
    sa.Column('wind_nagr', sa.String(length=5), nullable=False),
    sa.Column('sp_sneg_reg', sa.String(length=5), nullable=False),
    sa.Column('snow_nagr', sa.String(length=5), nullable=False),
    sa.Column('golol_rayon', sa.String(length=5), nullable=False),
    sa.Column('zasch_obj', sa.String(length=50), nullable=False),
    sa.Column('territoria_raspoloj', sa.String(length=50), nullable=False),
    sa.Column('rayon_str', sa.String(length=50), nullable=False),
    sa.Column('god_vvoda_v_ekspl', sa.String(length=5), nullable=False),
    sa.Column('quantity_of_rvs', sa.String(length=5), nullable=False),
    sa.Column('rvs1', sa.String(length=6), nullable=False),
    sa.Column('rvs2', sa.String(length=6), nullable=False),
    sa.Column('rvs3', sa.String(length=6), nullable=False),
    sa.Column('rvs4', sa.String(length=6), nullable=False),
    sa.Column('diam_osn1', sa.String(length=6), nullable=False),
    sa.Column('diam_osn2', sa.String(length=6), nullable=False),
    sa.Column('diam_osn3', sa.String(length=6), nullable=False),
    sa.Column('diam_osn4', sa.String(length=6), nullable=False),
    sa.Column('diam_verha1', sa.String(length=6), nullable=False),
    sa.Column('diam_verha2', sa.String(length=6), nullable=False),
    sa.Column('diam_verha3', sa.String(length=6), nullable=False),
    sa.Column('diam_verha4', sa.String(length=6), nullable=False),
    sa.Column('h1', sa.String(length=6), nullable=False),
    sa.Column('h2', sa.String(length=6), nullable=False),
    sa.Column('h3', sa.String(length=6), nullable=False),
    sa.Column('h4', sa.String(length=6), nullable=False),
    sa.Column('massa_rvs1', sa.String(length=6), nullable=False),
    sa.Column('massa_rvs2', sa.String(length=6), nullable=False),
    sa.Column('massa_rvs3', sa.String(length=6), nullable=False),
    sa.Column('massa_rvs4', sa.String(length=6), nullable=False),
    sa.Column('kol_rvs1', sa.String(length=5), nullable=False),
    sa.Column('kol_rvs2', sa.String(length=5), nullable=False),
    sa.Column('kol_rvs3', sa.String(length=5), nullable=False),
    sa.Column('kol_rvs4', sa.String(length=5), nullable=False),
    sa.Column('ploschad_uchastka1', sa.String(length=5), nullable=False),
    sa.Column('ploschad_uchastka2', sa.String(length=5), nullable=False),
    sa.Column('ploschad_uchastka3', sa.String(length=5), nullable=False),
    sa.Column('ploschad_uchastka4', sa.String(length=5), nullable=False),
    sa.Column('list_sogl', sa.Text(), nullable=False),
    sa.Column('kont_zazel', sa.Text(), nullable=False),
    sa.Column('mont_schema', sa.Text(), nullable=False),
    sa.Column('vid_kozu', sa.Text(), nullable=False),
    sa.Column('vid_kozu2', sa.Text(), nullable=False),
    sa.Column('vid_kozu3', sa.Text(), nullable=False),
    sa.Column('vid_kozu4', sa.Text(), nullable=False),
    sa.Column('speca', sa.Text(), nullable=False),
    sa.Column('speca_pz', sa.Text(), nullable=False),
    sa.Column('speca_pz2', sa.Text(), nullable=False),
    sa.Column('speca_pz3', sa.Text(), nullable=False),
    sa.Column('speca_pz4', sa.Text(), nullable=False),
    sa.Column('eskiz_kozu', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['initial_data_id'], ['initial_datas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kozu_project_datas')
    # ### end Alembic commands ###
