"""remove pole_defl field from rpzo table

Revision ID: 166958abf655
Revises: 241d77a63e8e
Create Date: 2023-11-17 13:15:28.993484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '166958abf655'
down_revision: Union[str, None] = '241d77a63e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpzo_datas', 'pole_defl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpzo_datas', sa.Column('pole_defl', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
