"""create rpzo, foundation, rpzf, anker tables

Revision ID: 241d77a63e8e
Revises: 9ccfdec330ed
Create Date: 2023-11-16 23:59:22.300226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241d77a63e8e'
down_revision: Union[str, None] = '9ccfdec330ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anker_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_data_id', sa.Integer(), nullable=False),
    sa.Column('bolt', sa.String(length=5), nullable=False),
    sa.Column('kol_boltov', sa.String(length=5), nullable=False),
    sa.Column('bolt_class', sa.String(length=5), nullable=False),
    sa.Column('hole_diam', sa.String(length=5), nullable=False),
    sa.Column('rast_m', sa.String(length=5), nullable=False),
    sa.Column('xlsx_bolt', sa.Text(), nullable=True),
    sa.Column('bolt_schema', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['initial_data_id'], ['initial_datas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foundation_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_data_id', sa.Integer(), nullable=False),
    sa.Column('bending_moment', sa.String(length=10), nullable=False),
    sa.Column('vert_force', sa.String(length=10), nullable=False),
    sa.Column('shear_force', sa.String(length=10), nullable=False),
    sa.Column('diam_svai', sa.String(length=5), nullable=False),
    sa.Column('thickness_svai', sa.String(length=10), nullable=True),
    sa.Column('deepness_svai', sa.String(length=10), nullable=False),
    sa.Column('height_svai', sa.String(length=5), nullable=False),
    sa.Column('is_initial_data', sa.Boolean(), nullable=False),
    sa.Column('typical_ground', sa.String(length=30), nullable=False),
    sa.Column('udel_sceplenie', sa.String(length=10), nullable=False),
    sa.Column('ugol_vntr_trenia', sa.String(length=10), nullable=False),
    sa.Column('ves_grunta', sa.String(length=10), nullable=True),
    sa.Column('deform_module', sa.String(length=10), nullable=True),
    sa.Column('ground_water_lvl', sa.String(length=10), nullable=True),
    sa.Column('quantity_of_sloy', sa.String(length=5), nullable=False),
    sa.Column('nomer_ige1', sa.String(length=10), nullable=False),
    sa.Column('nomer_ige2', sa.String(length=10), nullable=False),
    sa.Column('nomer_ige3', sa.String(length=10), nullable=False),
    sa.Column('nomer_ige4', sa.String(length=10), nullable=False),
    sa.Column('nomer_ige5', sa.String(length=10), nullable=False),
    sa.Column('ground_type1', sa.String(length=10), nullable=False),
    sa.Column('ground_type2', sa.String(length=10), nullable=False),
    sa.Column('ground_type3', sa.String(length=10), nullable=False),
    sa.Column('ground_type4', sa.String(length=10), nullable=False),
    sa.Column('ground_type5', sa.String(length=10), nullable=False),
    sa.Column('ground_name1', sa.String(length=20), nullable=False),
    sa.Column('ground_name2', sa.String(length=20), nullable=False),
    sa.Column('ground_name3', sa.String(length=20), nullable=False),
    sa.Column('ground_name4', sa.String(length=20), nullable=False),
    sa.Column('ground_name5', sa.String(length=20), nullable=False),
    sa.Column('verh_sloy1', sa.String(length=5), nullable=False),
    sa.Column('verh_sloy2', sa.String(length=5), nullable=False),
    sa.Column('verh_sloy3', sa.String(length=5), nullable=False),
    sa.Column('verh_sloy4', sa.String(length=5), nullable=False),
    sa.Column('verh_sloy5', sa.String(length=5), nullable=False),
    sa.Column('nijn_sloy1', sa.String(length=5), nullable=False),
    sa.Column('nijn_sloy2', sa.String(length=5), nullable=False),
    sa.Column('nijn_sloy3', sa.String(length=5), nullable=False),
    sa.Column('nijn_sloy4', sa.String(length=5), nullable=False),
    sa.Column('nijn_sloy5', sa.String(length=5), nullable=False),
    sa.Column('coef_poristosti1', sa.String(length=10), nullable=False),
    sa.Column('coef_poristosti2', sa.String(length=10), nullable=False),
    sa.Column('coef_poristosti3', sa.String(length=10), nullable=False),
    sa.Column('coef_poristosti4', sa.String(length=10), nullable=False),
    sa.Column('coef_poristosti5', sa.String(length=10), nullable=False),
    sa.Column('udel_scep1', sa.String(length=10), nullable=False),
    sa.Column('udel_scep2', sa.String(length=10), nullable=False),
    sa.Column('udel_scep3', sa.String(length=10), nullable=False),
    sa.Column('udel_scep4', sa.String(length=10), nullable=False),
    sa.Column('udel_scep5', sa.String(length=10), nullable=False),
    sa.Column('ugol_vn_tr1', sa.String(length=10), nullable=False),
    sa.Column('ugol_vn_tr2', sa.String(length=10), nullable=False),
    sa.Column('ugol_vn_tr3', sa.String(length=10), nullable=False),
    sa.Column('ugol_vn_tr4', sa.String(length=10), nullable=False),
    sa.Column('ugol_vn_tr5', sa.String(length=10), nullable=False),
    sa.Column('ves_gr_prir1', sa.String(length=10), nullable=False),
    sa.Column('ves_gr_prir2', sa.String(length=10), nullable=False),
    sa.Column('ves_gr_prir3', sa.String(length=10), nullable=False),
    sa.Column('ves_gr_prir4', sa.String(length=10), nullable=False),
    sa.Column('ves_gr_prir5', sa.String(length=10), nullable=False),
    sa.Column('def_mod1', sa.String(length=10), nullable=False),
    sa.Column('def_mod2', sa.String(length=10), nullable=False),
    sa.Column('def_mod3', sa.String(length=10), nullable=False),
    sa.Column('def_mod4', sa.String(length=10), nullable=False),
    sa.Column('def_mod5', sa.String(length=10), nullable=False),
    sa.Column('pole_type', sa.String(length=20), nullable=False),
    sa.Column('coef_nadej', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['initial_data_id'], ['initial_datas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpzf_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_data_id', sa.Integer(), nullable=False),
    sa.Column('ige_name', sa.Text(), nullable=False),
    sa.Column('building_adress', sa.Text(), nullable=False),
    sa.Column('razrez_skvajin', sa.String(length=50), nullable=False),
    sa.Column('picture1', sa.Text(), nullable=False),
    sa.Column('picture2', sa.Text(), nullable=False),
    sa.Column('xlsx_svai', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['initial_data_id'], ['initial_datas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpzo_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_data_id', sa.Integer(), nullable=False),
    sa.Column('wire_pos', sa.String(length=25), nullable=False),
    sa.Column('ground_wire_attachment', sa.String(length=25), nullable=False),
    sa.Column('quantity_of_ground_wire', sa.String(length=5), nullable=False),
    sa.Column('is_ground_wire_davit', sa.String(length=5), nullable=False),
    sa.Column('deflection', sa.String(length=10), nullable=True),
    sa.Column('pls_pole_pic1', sa.Text(), nullable=False),
    sa.Column('pls_pole_pic2', sa.Text(), nullable=False),
    sa.Column('pole_defl', sa.Text(), nullable=False),
    sa.Column('loads_1', sa.Text(), nullable=False),
    sa.Column('loads_2', sa.Text(), nullable=False),
    sa.Column('loads_3', sa.Text(), nullable=False),
    sa.Column('loads_4', sa.Text(), nullable=True),
    sa.Column('loads_5', sa.Text(), nullable=True),
    sa.Column('loads_6', sa.Text(), nullable=True),
    sa.Column('is_mont_schema', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['initial_data_id'], ['initial_datas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rpzo_datas')
    op.drop_table('rpzf_datas')
    op.drop_table('foundation_datas')
    op.drop_table('anker_datas')
    # ### end Alembic commands ###
