"""add kozup_datas

Revision ID: 972848c3d421
Revises: 0088aec53b0e
Create Date: 2025-07-14 10:31:00.598317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972848c3d421'
down_revision: Union[str, None] = '0088aec53b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kozup_project_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_data_id', sa.Integer(), nullable=False),
    sa.Column('sp_wind_reg', sa.String(length=5), nullable=False),
    sa.Column('wind_nagr', sa.String(length=5), nullable=False),
    sa.Column('golol_rayon', sa.String(length=5), nullable=False),
    sa.Column('zasch_obj', sa.String(length=50), nullable=False),
    sa.Column('territoria_raspoloj', sa.String(length=50), nullable=False),
    sa.Column('rayon_str', sa.String(length=50), nullable=False),
    sa.Column('expl_god', sa.String(length=5), nullable=False),
    sa.Column('v_m_bpla', sa.String(length=25), nullable=False),
    sa.Column('steel', sa.String(length=20), nullable=False),
    sa.Column('anal_steel', sa.String(length=20), nullable=False),
    sa.Column('konst', sa.Text(), nullable=False),
    sa.Column('kp_bolt', sa.String(length=15), nullable=False),
    sa.Column('fundament', sa.String(length=50), nullable=False),
    sa.Column('fund_osn', sa.String(length=60), nullable=False),
    sa.Column('kol_obj', sa.String(length=5), nullable=False),
    sa.Column('massa_obsch', sa.String(length=10), nullable=False),
    sa.Column('mont_vremya', sa.String(length=15), nullable=False),
    sa.Column('shag_yach', sa.String(length=10), nullable=False),
    sa.Column('post_nagr', sa.Text(), nullable=False),
    sa.Column('strela', sa.String(length=50), nullable=False),
    sa.Column('natyajenie', sa.String(length=50), nullable=False),
    sa.Column('klass_betona', sa.String(length=50), nullable=False),
    sa.Column('morozostoikost', sa.String(length=50), nullable=False),
    sa.Column('vodonepronicaemost', sa.String(length=50), nullable=False),
    sa.Column('quantity_of_obj', sa.String(length=5), nullable=False),
    sa.Column('dlina_elem', sa.String(length=10), nullable=False),
    sa.Column('zaschichaemyi_obj1', sa.String(length=20), nullable=False),
    sa.Column('zaschichaemyi_obj2', sa.String(length=20), nullable=False),
    sa.Column('zaschichaemyi_obj3', sa.String(length=20), nullable=False),
    sa.Column('zaschichaemyi_obj4', sa.String(length=20), nullable=False),
    sa.Column('length_kozup1', sa.String(length=20), nullable=False),
    sa.Column('length_kozup2', sa.String(length=20), nullable=False),
    sa.Column('length_kozup3', sa.String(length=20), nullable=False),
    sa.Column('length_kozup4', sa.String(length=20), nullable=False),
    sa.Column('width_kozup1', sa.String(length=20), nullable=False),
    sa.Column('width_kozup2', sa.String(length=20), nullable=False),
    sa.Column('width_kozup3', sa.String(length=20), nullable=False),
    sa.Column('width_kozup4', sa.String(length=20), nullable=False),
    sa.Column('h1', sa.String(length=20), nullable=False),
    sa.Column('h2', sa.String(length=20), nullable=False),
    sa.Column('h3', sa.String(length=20), nullable=False),
    sa.Column('h4', sa.String(length=20), nullable=False),
    sa.Column('massa_kozup1', sa.String(length=20), nullable=False),
    sa.Column('massa_kozup2', sa.String(length=20), nullable=False),
    sa.Column('massa_kozup3', sa.String(length=20), nullable=False),
    sa.Column('massa_kozup4', sa.String(length=20), nullable=False),
    sa.Column('speca', sa.Text(), nullable=False),
    sa.Column('vid_kozu_p1', sa.Text(), nullable=False),
    sa.Column('vid_kozu_p2', sa.Text(), nullable=True),
    sa.Column('vid_kozu_p3', sa.Text(), nullable=True),
    sa.Column('vid_kozu_p4', sa.Text(), nullable=True),
    sa.Column('table3', sa.Text(), nullable=False),
    sa.Column('table4', sa.Text(), nullable=False),
    sa.Column('table5', sa.Text(), nullable=False),
    sa.Column('table6', sa.Text(), nullable=False),
    sa.Column('raschet_model', sa.Text(), nullable=False),
    sa.Column('usiliya1', sa.Text(), nullable=False),
    sa.Column('usiliya2', sa.Text(), nullable=False),
    sa.Column('usiliya3', sa.Text(), nullable=False),
    sa.Column('usiliya4', sa.Text(), nullable=False),
    sa.Column('usiliya5', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['initial_data_id'], ['initial_datas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kozup_project_datas')
    # ### end Alembic commands ###
