"""add some fields

Revision ID: a796900b4ab6
Revises: 004f1500e67c
Create Date: 2023-12-10 20:18:43.436110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a796900b4ab6'
down_revision: Union[str, None] = '004f1500e67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anker_datas', sa.Column('flanec_diam', sa.String(length=5), nullable=False))
    op.add_column('anker_datas', sa.Column('diam_okr_bolt', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anker_datas', 'diam_okr_bolt')
    op.drop_column('anker_datas', 'flanec_diam')
    # ### end Alembic commands ###
