"""delete wire pos and attachment in rpzo table

Revision ID: af2a6abc9162
Revises: d3ec9839201e
Create Date: 2024-02-08 23:00:47.476064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af2a6abc9162'
down_revision: Union[str, None] = 'd3ec9839201e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpzo_datas', 'ground_wire_attachment')
    op.drop_column('rpzo_datas', 'wire_pos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpzo_datas', sa.Column('wire_pos', mysql.VARCHAR(length=25), nullable=False))
    op.add_column('rpzo_datas', sa.Column('ground_wire_attachment', mysql.VARCHAR(length=25), nullable=False))
    # ### end Alembic commands ###
