"""change nullable fields in foundation table

Revision ID: c27f222e9256
Revises: 166958abf655
Create Date: 2023-11-18 15:24:41.726551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c27f222e9256'
down_revision: Union[str, None] = '166958abf655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foundation_datas', 'typical_ground',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('foundation_datas', 'udel_sceplenie',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ugol_vntr_trenia',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'quantity_of_sloy',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('foundation_datas', 'nomer_ige1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'nomer_ige2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'nomer_ige3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'nomer_ige4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'nomer_ige5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ground_type1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ground_type2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ground_type3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ground_type4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ground_type5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ground_name1',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('foundation_datas', 'ground_name2',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('foundation_datas', 'ground_name3',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('foundation_datas', 'ground_name4',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('foundation_datas', 'ground_name5',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('foundation_datas', 'verh_sloy1',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('foundation_datas', 'verh_sloy2',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('foundation_datas', 'verh_sloy3',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('foundation_datas', 'verh_sloy4',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('foundation_datas', 'verh_sloy5',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('foundation_datas', 'nijn_sloy1',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('foundation_datas', 'nijn_sloy2',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('foundation_datas', 'nijn_sloy3',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('foundation_datas', 'nijn_sloy4',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('foundation_datas', 'nijn_sloy5',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    op.alter_column('foundation_datas', 'coef_poristosti1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'coef_poristosti2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'coef_poristosti3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'coef_poristosti4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'coef_poristosti5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'udel_scep1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'udel_scep2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'udel_scep3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'udel_scep4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'udel_scep5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ugol_vn_tr1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ugol_vn_tr2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ugol_vn_tr3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ugol_vn_tr4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ugol_vn_tr5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ves_gr_prir1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ves_gr_prir2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ves_gr_prir3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ves_gr_prir4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'ves_gr_prir5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'def_mod1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'def_mod2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'def_mod3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'def_mod4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('foundation_datas', 'def_mod5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foundation_datas', 'def_mod5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'def_mod4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'def_mod3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'def_mod2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'def_mod1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ves_gr_prir5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ves_gr_prir4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ves_gr_prir3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ves_gr_prir2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ves_gr_prir1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ugol_vn_tr5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ugol_vn_tr4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ugol_vn_tr3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ugol_vn_tr2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ugol_vn_tr1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'udel_scep5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'udel_scep4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'udel_scep3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'udel_scep2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'udel_scep1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'coef_poristosti5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'coef_poristosti4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'coef_poristosti3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'coef_poristosti2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'coef_poristosti1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'nijn_sloy5',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('foundation_datas', 'nijn_sloy4',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('foundation_datas', 'nijn_sloy3',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('foundation_datas', 'nijn_sloy2',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('foundation_datas', 'nijn_sloy1',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('foundation_datas', 'verh_sloy5',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('foundation_datas', 'verh_sloy4',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('foundation_datas', 'verh_sloy3',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('foundation_datas', 'verh_sloy2',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('foundation_datas', 'verh_sloy1',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('foundation_datas', 'ground_name5',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('foundation_datas', 'ground_name4',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('foundation_datas', 'ground_name3',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('foundation_datas', 'ground_name2',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('foundation_datas', 'ground_name1',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('foundation_datas', 'ground_type5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ground_type4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ground_type3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ground_type2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'ground_type1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'nomer_ige5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'nomer_ige4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'nomer_ige3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'nomer_ige2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'nomer_ige1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'quantity_of_sloy',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('foundation_datas', 'ugol_vntr_trenia',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'udel_sceplenie',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('foundation_datas', 'typical_ground',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
