"""add passport pkpo table, add 2 fields to initial data

Revision ID: d3ec9839201e
Revises: a796900b4ab6
Create Date: 2024-02-05 17:27:00.027822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ec9839201e'
down_revision: Union[str, None] = 'a796900b4ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pasport_pkpo_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_data_id', sa.Integer(), nullable=False),
    sa.Column('kol_kkm', sa.String(length=5), nullable=False),
    sa.Column('kol_ap_zaj_opn', sa.String(length=5), nullable=False),
    sa.Column('kol_ap_zaj_km', sa.String(length=5), nullable=False),
    sa.Column('kol_otv_zaj', sa.String(length=5), nullable=False),
    sa.Column('kol_opn', sa.String(length=5), nullable=False),
    sa.Column('kol_kab_krep', sa.String(length=5), nullable=True),
    sa.Column('konc_kor', sa.String(length=15), nullable=True),
    sa.Column('kol_konc_kor', sa.String(length=5), nullable=False),
    sa.Column('ppsa', sa.String(length=15), nullable=False),
    sa.Column('ppsa_length', sa.String(length=5), nullable=False),
    sa.Column('kol_skoba_bol', sa.String(length=5), nullable=False),
    sa.Column('kol_skoba_mal', sa.String(length=5), nullable=False),
    sa.Column('kol_styajka', sa.String(length=5), nullable=False),
    sa.Column('razed', sa.Boolean(), nullable=False),
    sa.Column('syst_telemekh', sa.Boolean(), nullable=False),
    sa.Column('izmerit_ustr', sa.Boolean(), nullable=False),
    sa.Column('panel_rel_zasch', sa.Boolean(), nullable=False),
    sa.Column('syst_sobstv_nujd', sa.Boolean(), nullable=False),
    sa.Column('syst_temp_monit', sa.Boolean(), nullable=False),
    sa.Column('obor_antiterror', sa.Boolean(), nullable=False),
    sa.Column('rezerv_kabelya', sa.Boolean(), nullable=False),
    sa.Column('vch_vols', sa.Boolean(), nullable=False),
    sa.Column('akep', sa.String(length=10), nullable=False),
    sa.Column('sech_jili', sa.String(length=10), nullable=False),
    sa.Column('sech_ekr', sa.String(length=10), nullable=False),
    sa.Column('sech_al_prov', sa.String(length=10), nullable=False),
    sa.Column('naib_rab_voltage', sa.String(length=10), nullable=False),
    sa.Column('naib_dlit_dop_rab_voltage', sa.String(length=10), nullable=False),
    sa.Column('oprosniy_list', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['initial_data_id'], ['initial_datas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('initial_datas', sa.Column('wire_pos', sa.String(length=25), nullable=False))
    op.add_column('initial_datas', sa.Column('ground_wire_attachment', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('initial_datas', 'ground_wire_attachment')
    op.drop_column('initial_datas', 'wire_pos')
    op.drop_table('pasport_pkpo_datas')
    # ### end Alembic commands ###
