from sqlalchemy import Column, Integer, String, ForeignKey, Boolean, Text
from sqlalchemy.orm import declarative_base


Base = declarative_base()


class InitialDatas(Base):
    __tablename__ = "initial_datas"
    id = Column(Integer, primary_key=True)
    project_name = Column(Text, nullable=False)
    project_code = Column(String(15), nullable=False)
    pole_code = Column(String(25), nullable=False)
    pole_type = Column(String(15), nullable=False)
    developer = Column(String(20), nullable=False)
    voltage = Column(String(5), nullable=False)
    area_type = Column(String(5), nullable=False)
    branch = Column(String(5), nullable=False)
    wind_area = Column(String(5), nullable=False)
    wind_pressure = Column(String(5), nullable=False)
    ice_area = Column(String(5), nullable=False)
    ice_thickness = Column(String(5), nullable=False)
    ice_wind_pressure = Column(String(5), nullable=False)
    wind_reg_coef = Column(String(5), nullable=False)
    ice_reg_coef = Column(String(5), nullable=False)
    wire_hesitation = Column(String(25), nullable=False)
    avg_temp = Column(String(10), nullable=False)
    min_temp = Column(String(10), nullable=False)
    max_temp = Column(String(10), nullable=False)
    ice_temp = Column(String(10), nullable=False)
    wind_temp = Column(String(10), nullable=False)
    wire = Column(String(20), nullable=False)
    wire_tension = Column(String(10), nullable=False)
    ground_wire = Column(String(50), nullable=True)
    oksn = Column(String(50), nullable=True)
    wind_span = Column(String(5), nullable=False)
    weight_span = Column(String(5), nullable=False)
    is_stand = Column(Boolean, nullable=False)
    is_plate = Column(Boolean, nullable=False)
    txt_1 = Column(Text, nullable=False)
    txt_2 = Column(Text, nullable=False)


class RpzoDatas(Base):
    __tablename__ = "rpzo_datas"
    id = Column(Integer, primary_key=True)
    initial_data_id = Column(Integer, ForeignKey("initial_datas.id"), nullable=False)
    wire_pos = Column(String(25), nullable=False)
    ground_wire_attachment = Column(String(25), nullable=False)
    quantity_of_ground_wire = Column(String(5), nullable=False)
    is_ground_wire_davit = Column(String(5), nullable=False)
    deflection = Column(String(10), nullable=True)
    pls_pole_pic1 = Column(Text, nullable=False)
    pls_pole_pic2 = Column(Text, nullable=False)
    pole_defl = Column(Text, nullable=False)
    loads_1 = Column(Text, nullable=False)
    loads_2 = Column(Text, nullable=False)
    loads_3 = Column(Text, nullable=False)
    loads_4 = Column(Text, nullable=True)
    loads_5 = Column(Text, nullable=True)
    loads_6 = Column(Text, nullable=True)
    is_mont_schema = Column(Text, nullable=False)


class FoundationDatas(Base):
    __tablename__ = "foundation_datas"
    id = Column(Integer, primary_key=True)
    initial_data_id = Column(Integer, ForeignKey("initial_datas.id"), nullable=False)
    bending_moment = Column(String(10), nullable=False)
    vert_force = Column(String(10), nullable=False)
    shear_force = Column(String(10), nullable=False)
    diam_svai = Column(String(5), nullable=False)
    thickness_svai = Column(String(10), nullable=True)
    deepness_svai = Column(String(10), nullable=False)
    height_svai = Column(String(5), nullable=False)
    is_initial_data = Column(Boolean, nullable=False)
    typical_ground = Column(String(30), nullable=False)
    udel_sceplenie = Column(String(10), nullable=False)
    ugol_vntr_trenia = Column(String(10), nullable=False)
    ves_grunta = Column(String(10), nullable=True)
    deform_module = Column(String(10), nullable=True)
    ground_water_lvl = Column(String(10), nullable=True)
    quantity_of_sloy = Column(String(5), nullable=False)
    nomer_ige1 = Column(String(10), nullable=False)
    nomer_ige2 = Column(String(10), nullable=False)
    nomer_ige3 = Column(String(10), nullable=False)
    nomer_ige4 = Column(String(10), nullable=False)
    nomer_ige5 = Column(String(10), nullable=False)
    ground_type1 = Column(String(10), nullable=False)
    ground_type2 = Column(String(10), nullable=False)
    ground_type3 = Column(String(10), nullable=False)
    ground_type4 = Column(String(10), nullable=False)
    ground_type5 = Column(String(10), nullable=False)
    ground_name1 = Column(String(20), nullable=False)
    ground_name2 = Column(String(20), nullable=False)
    ground_name3 = Column(String(20), nullable=False)
    ground_name4 = Column(String(20), nullable=False)
    ground_name5 = Column(String(20), nullable=False)
    verh_sloy1 = Column(String(5), nullable=False)
    verh_sloy2 = Column(String(5), nullable=False)
    verh_sloy3 = Column(String(5), nullable=False)
    verh_sloy4 = Column(String(5), nullable=False)
    verh_sloy5 = Column(String(5), nullable=False)
    nijn_sloy1 = Column(String(5), nullable=False)
    nijn_sloy2 = Column(String(5), nullable=False)
    nijn_sloy3 = Column(String(5), nullable=False)
    nijn_sloy4 = Column(String(5), nullable=False)
    nijn_sloy5 = Column(String(5), nullable=False)
    coef_poristosti1 = Column(String(10), nullable=False)
    coef_poristosti2 = Column(String(10), nullable=False)
    coef_poristosti3 = Column(String(10), nullable=False)
    coef_poristosti4 = Column(String(10), nullable=False)
    coef_poristosti5 = Column(String(10), nullable=False)
    udel_scep1 = Column(String(10), nullable=False)
    udel_scep2 = Column(String(10), nullable=False)
    udel_scep3 = Column(String(10), nullable=False)
    udel_scep4 = Column(String(10), nullable=False)
    udel_scep5 = Column(String(10), nullable=False)
    ugol_vn_tr1 = Column(String(10), nullable=False)
    ugol_vn_tr2 = Column(String(10), nullable=False)
    ugol_vn_tr3 = Column(String(10), nullable=False)
    ugol_vn_tr4 = Column(String(10), nullable=False)
    ugol_vn_tr5 = Column(String(10), nullable=False)
    ves_gr_prir1 = Column(String(10), nullable=False)
    ves_gr_prir2 = Column(String(10), nullable=False)
    ves_gr_prir3 = Column(String(10), nullable=False)
    ves_gr_prir4 = Column(String(10), nullable=False)
    ves_gr_prir5 = Column(String(10), nullable=False)
    def_mod1 = Column(String(10), nullable=False)
    def_mod2 = Column(String(10), nullable=False)
    def_mod3 = Column(String(10), nullable=False)
    def_mod4 = Column(String(10), nullable=False)
    def_mod5 = Column(String(10), nullable=False)
    pole_type = Column(String(20), nullable=False)
    coef_nadej = Column(String(5), nullable=False)


class RpzfDatas(Base):
    __tablename__ = "rpzf_datas"
    id = Column(Integer, primary_key=True)
    initial_data_id = Column(Integer, ForeignKey("initial_datas.id"), nullable=False)
    ige_name = Column(Text, nullable=False)
    building_adress = Column(Text, nullable=False)
    razrez_skvajin = Column(String(50), nullable=False)
    picture1 = Column(Text, nullable=False)
    picture2 = Column(Text, nullable=False)
    xlsx_svai = Column(Text, nullable=False)


class AnkerDatas(Base):
    __tablename__ = "anker_datas"
    id = Column(Integer, primary_key=True)
    initial_data_id = Column(Integer, ForeignKey("initial_datas.id"), nullable=False)
    bolt = Column(String(5), nullable=False)
    kol_boltov = Column(String(5), nullable=False)
    bolt_class = Column(String(5), nullable=False)
    hole_diam = Column(String(5), nullable=False)
    rast_m = Column(String(5), nullable=False)
    xlsx_bolt = Column(Text, nullable=True)
    bolt_schema = Column(Text, nullable=True)